create database Indra
go

USE Indra
GO

CREATE TABLE Prioridad
(
PRI_Id INTEGER PRIMARY KEY,
Pri_Descripcion VARCHAR(45)
)
go

CREATE TABLE Servicio
(
SER_Id	INTEGER IDENTITY(1,1) PRIMARY KEY,
SER_Descripcion	VARCHAR(45)
)
go

CREATE TABLE TipoProblema
(
PRO_Id	INTEGER IDENTITY(1,1) PRIMARY KEY,
PRO_Descripcion	VARCHAR(45),
SER_Id		INTEGER FOREIGN KEY REFERENCES Servicio(SER_Id)
)
go

CREATE TABLE Categoria
(
CAT_ID	INTEGER IDENTITY(1,1) PRIMARY KEY,
CAT_Descripcion	VARCHAR(150)
)
go


CREATE TABLE TipoSolucion
(
SOL_Id INTEGER IDENTITY(1,1) PRIMARY KEY,
SOL_PROD_Id	INTEGER FOREIGN KEY REFERENCES TipoProblema(PRO_Id),
SOL_Descripcion	VARCHAR(45),
SOL_RutaArchivo	VARCHAR(45),
SOL_DescripcionLarga	VARCHAR(1000),
SOL_CAT_ID INTEGER FOREIGN KEY REFERENCES Categoria(CAT_ID),
SOL_FechaCreacion	DATETIME,
SOL_UsuarioCreacion	VARCHAR(50)
)
go

CREATE TABLE Empresa
(
EMP_Id	INTEGER IDENTITY(1,1) PRIMARY KEY,
EMP_RUC	NUMERIC(12,0),
EMP_RazonSocial	VARCHAR(250)
)
go

CREATE TABLE UsuarioCliente
(
USU_Id INTEGER IDENTITY PRIMARY KEY,
USU_IdLogin VARCHAR(50),
USU_EMP_Id	INTEGER FOREIGN KEY REFERENCES Empresa(EMP_Id),
USU_Nombre	VARCHAR(80),
USU_ApellidoPaterno	VARCHAR(80),
USU_ApellidoMaterno	VARCHAR(80),
USU_Telefono	Varchar(15),
USU_Email		Varchar(60)
)
go

CREATE TABLE Cargo
(
CAR_Id INTEGER IDENTITY(1,1) PRIMARY KEY,
CAR_Descripcion	VARCHAR(80)
)
go

CREATE TABLE Nivel
(
NIV_Id INTEGER IDENTITY(1,1) PRIMARY KEY,
NIV_Descripcion	VARCHAR(80)
)
go

CREATE TABLE UsuarioResponsable
(
RES_Id	INTEGER IDENTITY PRIMARY KEY,
RES_IdLogin	VARCHAR(45),
RES_CAR_Id	INTEGER FOREIGN KEY REFERENCES Cargo(CAR_Id),
RES_Nombre	Varchar(80),
RES_ApellidoPaterno	VARCHAR(80),
RES_ApellidoMaterno	VARCHAR(80),
RES_Email		Varchar(60),
RES_NIV_Id	INTEGER FOREIGN KEY REFERENCES Nivel(NIV_Id)
)
go

CREATE TABLE Estado
(
EST_Id SMALLINT PRIMARY KEY,
EST_Descripcion	Varchar(50)
)
go

CREATE TABLE TipoEncuesta
(
TEN_Id	INTEGER IDENTITY(1,1) PRIMARY KEY,
TEN_Nombre	VARCHAR(45)
)
go

CREATE TABLE Pregunta
(
PRE_Id	INTEGER IDENTITY(1,1) PRIMARY KEY,
PRE_Descripcion VARCHAR(200),
PRE_TipoControl INT,
PRE_TEN_Id INTEGER FOREIGN KEY REFERENCES TipoEncuesta(TEN_Id),
PRE_FlagActivo	BIT
)
go

CREATE TABLE Encuesta
(
ENC_Id INTEGER IDENTITY(1,1) PRIMARY KEY,
ENC_Nombre VARCHAR(45),
ENC_Descripcion VARCHAR(100),
ENC_FlagActivo BIT,
ENC_TEN_Id INTEGER FOREIGN KEY REFERENCES TipoEncuesta(TEN_Id),
ENC_FlagEnvio BIT NULL
)
go

CREATE TABLE Ticket
(
TIC_Id	INTEGER IDENTITY(1,1) PRIMARY KEY,
TIC_PRI_Id	INTEGER FOREIGN KEY REFERENCES Prioridad(PRI_ID),
TIC_PRO_Id INTEGER FOREIGN KEY REFERENCES TipoProblema(PRO_Id),
TIC_SOL_Id	INTEGER	FOREIGN KEY REFERENCES TipoSolucion(SOL_Id),
TIC_SER_Id	INTEGER	FOREIGN KEY REFERENCES Servicio(SER_Id),
TIC_EMP_Id	INTEGER	FOREIGN KEY REFERENCES Empresa(EMP_Id),
TIC_USU_Id	INTEGER	FOREIGN KEY REFERENCES UsuarioCliente(USU_Id),
TIC_Descripcion VARCHAR(5000),
TIC_FechaRegistro	DATETIME,
TIC_FechaCierre	DATETIME,
TIC_CodigoEstado	SMALLINT FOREIGN KEY REFERENCES Estado(EST_Id),
TIC_ENC_Id	INT NULL FOREIGN KEY REFERENCES Encuesta
)
go

CREATE TABLE Resultado
(
RST_Id	INT	IDENTITY(1,1) PRIMARY KEY,
RST_Descripcion	VARCHAR(5000),
RST_FlagExito	BIT
)
go

CREATE TABLE Atencion
(
ATE_ID		INTEGER IDENTITY(1,1),
ATE_TIC_Id	INTEGER FOREIGN KEY REFERENCES Ticket(TIC_Id),
ATE_RES_Id	INTEGER FOREIGN KEY REFERENCES UsuarioResponsable(RES_Id),
ATE_RST_Id	INTEGER	FOREIGN KEY REFERENCES Resultado(RST_ID),
ATE_FechaAsignacion	DATETIME,
ATE_FechaInicio	DATETIME,
ATE_FechaFin	DATETIME,
ATE_FechaCierre	DATETIME,
ATE_FechaAtencion	DATETIME,
ATE_PRI_Id	INTEGER,
ATE_TIC_Descripcion VARCHAR(5000),
ATE_FechaRegistro	DATETIME
PRIMARY KEY(ATE_ID,ATE_TIC_Id,ATE_RES_Id)
)
go

CREATE TABLE HistorialTicket
(
HIS_ID		INTEGER,
HIS_TIC_ID	INTEGER,
HIS_PRI_Id	INTEGER,
HIS_PRO_Id INTEGER,
HIS_SER_Id	INTEGER,
HIS_RES_Id	INTEGER,
HIS_FechaCambio	DATETIME,
HIS_Descripcion VARCHAR(500),
HIS_RutaInforme	VARCHAR(100)
)
